//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BdBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LIBRO
    {

        [ScaffoldColumn(false)]
        public int id_libro { get; set; }


        [DataType(DataType.Text)] // nos define cual es el tipo q utilizamos
        [Required(ErrorMessage = "El título es requerido"), MaxLength(20)] //sea obligatorio 
        [Display(Name = "Título")]
        public string titulo { get; set; }

        [DataType(DataType.Text)] // nos define cual es el tipo q utilizamos
        [Required(ErrorMessage = "El autor(es) es requerido"), MaxLength(80)] //sea obligatorio 
        [Display(Name = "Autor(es)")]
        public string autor { get; set; }


        [DataType(DataType.Text)] // nos define cual es el tipo q utilizamos
        [Required(ErrorMessage = "El ISBN es requerido"), MaxLength(20)] //sea obligatorio 
        [Display(Name = "ISBN")]
        public string ISBN { get; set; }

        [Display(Name = "Fecha de publicación")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public System.DateTime fechaPublicacion { get; set; }


        [DataType(DataType.Duration)] // nos define cual es el tipo q utilizamos
        [Required(ErrorMessage = "La cantidad de ejemplares es requerida")] //sea obligatorio 
        [Display(Name = "Cantidad de ejemplares:")]
        public string ejemplar { get; set; }

        [DataType(DataType.Text)] // nos define cual es el tipo q utilizamos
        [Required(ErrorMessage = "La categoría es requerida")] //sea obligatorio 
        [Display(Name = "Categoría")]
        public int categoria { get; set; }
    
        public virtual CATEGORIA CATEGORIA1 { get; set; }
    }
}
