//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BdBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VIDEO
    {

        [ScaffoldColumn(false)]
        public int id_video { get; set; }

        [DataType(DataType.Text)] // nos define cual es el tipo q utilizamos
        [Required(ErrorMessage = "El título es requerido"), MaxLength(20)] //sea obligatorio 
        [Display(Name = "Título")]
        public string titulo { get; set; }

        [Display(Name = "Fecha de publicación")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public System.DateTime fechaPublicacion { get; set; }

        [DataType(DataType.Text)] // nos define cual es el tipo q utilizamos
        [Required(ErrorMessage = "El formato es requerido"), MaxLength(20)] //sea obligatorio 
        [Display(Name = "Formato")]
        public string formato { get; set; }


        
        [Required(ErrorMessage = "La duración")] //sea obligatorio 
        [Display(Name = "Duración")]
        public double duracion { get; set; }


        [DataType(DataType.Text)] // nos define cual es el tipo q utilizamos
        [Required(ErrorMessage = "La categoría es requerida")] //sea obligatorio 
        [Display(Name = "Categoría")]
        public int categoria { get; set; }
    
        public virtual CATEGORIA CATEGORIA1 { get; set; }
    }
}
